version: '3.8'
services:
  carash-server:
    build: 
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "8280:8280"
    container_name: carash-server
    volumes:
      - ./Server:/usr/src/app

  carash-client:
    build: 
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "8230:8230"
    container_name: carash-client

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"   # 將 Nginx 的 80 端口映射到主機的 8080 端口
      - "8443:443"  # HTTPS
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - carash-server
      - carash-client
    container_name: nginx-proxy
